builds:
    - binary: minify
      main: ./cmd/minify/
      ldflags: -s -w -X main.Version={{if eq .Version "devel"}}devel +{{printf "%.7s" .Commit}} {{.Date}}{{else}}minify{{.Version}}{{end}}
      goos:
          - windows
          - linux
          - darwin
      goarch:
          - amd64
          - 386
          - arm
          - arm64
fpm:
    vendor: "github.com/tdewolff/minify"
    maintainer: "Taco de Wolff <tacodewolff@gmail.com>"
    description: "Go minifiers for web formats"
    license: "MIT"
    formats:
        - deb
        - rpm
archive:
    format: tar.gz
    format_overrides:
        - goos: windows
          format: zip
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    files:
        - README.md
        - LICENSE.md
snapshot:
    name_template: "devel"
release:
    draft: true
