language: go
before_install:
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN -package=". ./css ./html ./js ./json ./svg ./xml" || go test -v ./...